Repository AstroDogeDX/ShibaStation-GS, pull requests merged in 2025-03, with the labels that each got.

#132 Fixed locale regarding IPC APC pop-up
  Resources/Locale/en-US/_EinsteinEngines/power/silicons.ftl
Labels: S: Untriaged, size/XS, Changes: No C#

#138 Air Alarm 'Cycling' Mode Improvements
  Content.Client/Atmos/Monitor/UI/AirAlarmWindow.xaml.cs
  Content.Server/Atmos/Monitor/Systems/AirAlarmModes.cs
  Content.Shared/Atmos/Monitor/Components/SharedAirAlarmComponent.cs
Labels: Changes: UI, S: Untriaged, size/S

#139 Leporazine works on dead mobs
  Resources/Prototypes/Reagents/medicine.yml
Labels: S: Untriaged, size/S, Changes: No C#

#140 Removed Redundant Gas Filters + CentComm Update
  Resources/Maps/_ShibaStation/amber.yml
  Resources/Maps/_ShibaStation/centcomm.yml
  Resources/Maps/_ShibaStation/cluster.yml
  Resources/Maps/_ShibaStation/omega.yml
  Resources/Maps/_ShibaStation/packed.yml
  Resources/Maps/_ShibaStation/saltern.yml
Labels: Changes: Map, S: Untriaged, size/L, Changes: No C#

#142 Remove Lavaland Shuttle / Salvage Shuttle FTLs to Lavaland / Salvage Shuttle Spawns Docked To Station
  Content.Server/_Lavaland/Shuttles/Systems/DockingConsoleSystem.cs
  Resources/Locale/en-US/deltav/shuttles/docking-console.ftl
  Resources/Maps/Shuttles/mining.yml
  Resources/Maps/_Lavaland/mining.yml
  Resources/Maps/_ShibaStation/Lavaland/outpost_lavaland_big.yml
  Resources/Maps/_ShibaStation/amber.yml
  Resources/Maps/_ShibaStation/atlas.yml
  Resources/Maps/_ShibaStation/cluster.yml
  Resources/Maps/_ShibaStation/elkridge.yml
  Resources/Maps/_ShibaStation/omega.yml
  Resources/Maps/_ShibaStation/packed.yml
  Resources/Maps/_ShibaStation/saltern.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/_Lavaland/Entities/Structures/airlocks.yml
  Resources/Prototypes/_Lavaland/Entities/Structures/computers.yml
  Resources/Prototypes/_Lavaland/Procedural/lavaland_planets.yml
Labels: Changes: Map, S: Untriaged

#146 Make ethyl medipens inject their full amount
  Resources/Prototypes/_ShibaStation/Entities/Objects/Specific/Medical/hypospray.yml
Labels: size/XS, Changes: No C#

#145 Switch back to our less memey aliem names
  Resources/Prototypes/_Shitmed/Entities/Mobs/Player/abductor.yml
  Resources/Prototypes/_Shitmed/GameRules/events.yml
Labels: size/S, Changes: No C#

#144 More mapping tweaks
  Resources/Maps/_ShibaStation/amber.yml
  Resources/Maps/_ShibaStation/cluster.yml
  Resources/Maps/_ShibaStation/omega.yml
  Resources/Maps/_ShibaStation/packed.yml
Labels: Changes: Map, size/L, Changes: No C#

#147 Felind and Oni Tag Fix
  Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/Oni.yml
  Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
Labels: size/XS, Changes: No C#

#148 Rolly chair spawners and mapping
  Resources/Maps/_ShibaStation/amber.yml
  Resources/Maps/_ShibaStation/cluster.yml
  Resources/Maps/_ShibaStation/omega.yml
  Resources/Maps/_ShibaStation/packed.yml
  Resources/Prototypes/_ShibaStation/Entities/Markers/Spawners/vehicles.yml
Labels: Changes: Map, S: Untriaged, size/M, Changes: No C#

#149 Adjustments to Felinid, Rodentia, Tajara, and their guidebooks, plus animal poison changes.
  Resources/Prototypes/Guidebook/species.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
  Resources/Prototypes/_Goobstation/Entities/Mobs/Species/tajaran.yml
  Resources/ServerInfo/Guidebook/Mobs/Felinid.xml
  Resources/ServerInfo/Guidebook/Mobs/Species.xml
  Resources/ServerInfo/Guidebook/Mobs/Tajaran.xml
  Resources/ServerInfo/Guidebook/Mobs/_DV/Rodentia.xml
Labels: S: Untriaged, Changes: No C#

#152 New lobbysong
  Resources/Audio/_ShibaStation/Lobby/attributions.yml
  Resources/Audio/_ShibaStation/Lobby/shibastation.ogg
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: S: Untriaged, S: Needs Review, size/XS, Changes: No C#, Changes: Audio

#150 Tag Fixes & Typo Correction
  Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
  Resources/Prototypes/_DV/Entities/Mobs/Species/harpy.yml
  Resources/Prototypes/_DV/Entities/Mobs/Species/vulpkanin.yml
  Resources/ServerInfo/Guidebook/Mobs/Species.xml
Labels: S: Untriaged, size/XS, Changes: No C#

#159 Allow Shutter and Blast Door Frames to Be Rotated During Construction
  Resources/Prototypes/Entities/Structures/Doors/Shutter/blast_door.yml
  Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#155 Spraypainter more atmos colors
  Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#153 Add song to jukebox
  Resources/Prototypes/Catalog/Jukebox/Standard.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#158 Fix missing name / description of contraband detector in construction…
  Resources/Prototypes/_Goobstation/Recipes/Construction/contraband_detector.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#161 Add basic parts to some techfabs
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/_Goobstation/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/cargo.yml
  Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/medical.yml
  Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/service.yml
Labels: S: Untriaged, size/S, Changes: No C#

#162 Adds BSO CQC manual to the BSO locker
  Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#163 ;Eng to Sci! lobby art
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/_ShibaStation/LobbyScreens/good_day_in_science.webp
  Resources/Textures/_ShibaStation/LobbyScreens/good_day_in_science.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#165 Animal organs are trash (and mouse stomachs are edible)
  Resources/Prototypes/Body/Organs/Animal/animal.yml
Labels: S: Untriaged, Changes: No C#

#166 Make Admeme Loadout Great Again
  Resources/Prototypes/_ShibaStation/Roles/Jobs/CentComm/chief_central_commander.yml
Labels: size/S, Changes: No C#

#167 [Early Merge] Cherrypicked NanoChat Updates
  Content.Client/_DV/CartridgeLoader/Cartridges/NanoChatLookupView.xaml
  Content.Client/_DV/CartridgeLoader/Cartridges/NanoChatLookupView.xaml.cs
  Content.Client/_DV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml
  Content.Client/_DV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
  Content.Server/_DV/CartridgeLoader/Cartridges/NanoChatCartridgeSystem.cs
  Content.Shared/_DV/CartridgeLoader/Cartridges/NanoChatUiMessageEvent.cs
  Content.Shared/_DV/CartridgeLoader/Cartridges/NanoChatUiState.cs
  Content.Shared/_DV/NanoChat/NanoChatCardComponent.cs
  Content.Shared/_DV/NanoChat/SharedNanoChatSystem.cs
  Resources/Locale/en-US/_DV/deltav/cartridge-loader/cartridges.ftl
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Textures/_DV/Interface/VerbIcons/ATTRIBUTION.txt
  Resources/Textures/_DV/Interface/VerbIcons/hamburger_icon.svg.png
Labels: Changes: UI, S: Untriaged, size/M

#168 Fax machine minor animation fix
  Resources/Textures/Structures/Machines/fax_machine.rsi/inserting_hamster.png
  Resources/Textures/Structures/Machines/fax_machine.rsi/inserting_mothroach.png
  Resources/Textures/Structures/Machines/fax_machine.rsi/inserting_mouse.png
Labels: Changes: Sprites, S: Untriaged, size/XS, Changes: No C#

#171 Anomaly Admin Logging
  Content.Server/Anomaly/AnomalySystem.Generator.cs
  Content.Server/StationEvents/Events/AnomalySpawnRule.cs
  Resources/Prototypes/Entities/Markers/Spawners/Random/anomaly.yml
Labels: S: Untriaged, size/M

#170 Various antag/event tweaks to make them more common
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/midround.yml
  Resources/Prototypes/GameRules/random_sentience.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
  Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
  Resources/Prototypes/_Shitmed/GameRules/events.yml
Labels: size/S, Changes: No C#

#172 Added Akuji & Miccau Plushies (+ Other Plushie Fixes)
  Resources/Maps/_ShibaStation/centcomm.yml
  Resources/Prototypes/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/arcades.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_achto.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_cass.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_dave.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_deroh.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_lucy.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/akuji_plushie.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/miccau_plushie.yml
  Resources/Textures/_ShibaStation/Objects/Fun/akujiplush.rsi/akuji-cc.png
  Resources/Textures/_ShibaStation/Objects/Fun/akujiplush.rsi/akuji.png
  Resources/Textures/_ShibaStation/Objects/Fun/akujiplush.rsi/meta.json
  Resources/Textures/_ShibaStation/Objects/Fun/miccauplush.rsi/meta.json
  Resources/Textures/_ShibaStation/Objects/Fun/miccauplush.rsi/miccau.png
Labels: Changes: Sprites, Changes: Map, S: Untriaged, size/M, Changes: No C#

#173 Improved Anomaly/Gas Leak Announcements; Expanded Admin Logs
  Content.Server/Anomaly/AnomalySystem.Generator.cs
  Content.Server/StationEvents/Events/GasLeakRule.cs
Labels: S: Untriaged, size/S

#174 Dave Plushie Update
  Resources/Audio/_ShibaStation/Effects/attributions.yml
  Resources/Audio/_ShibaStation/Effects/dave_oof.ogg
  Resources/Audio/_ShibaStation/Effects/dave_saying_boneappletea.ogg
  Resources/Audio/_ShibaStation/Effects/dave_saying_dude.ogg
  Resources/Audio/_ShibaStation/Effects/dave_saying_pizzadelivery.ogg
  Resources/Audio/_ShibaStation/Effects/dave_saying_wassup.ogg
  Resources/Audio/_ShibaStation/Effects/dave_wee.ogg
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_dave.yml
  Resources/Prototypes/_ShibaStation/SoundCollections/dave_plush_soundcollection.yml
Labels: S: Untriaged, size/S, Changes: No C#, Changes: Audio

#176 Fixed Cluster
  Resources/Maps/_ShibaStation/cluster.yml
Labels: Changes: Map, S: Untriaged, size/XS, Changes: No C#

#178 Lavaland Bluespace Shelter Fix
  Content.Server/_Lavaland/Salvage/ShelterCapsuleSystem.cs
Labels: S: Untriaged, size/S

#180 Ore Processor Point Gen Tweaks
  Content.Shared/_DV/Salvage/Systems/MiningPointsSystem.cs
Labels: S: Untriaged, size/S

#181 Disabled carrying on all species
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
  Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
  Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml
  Resources/Prototypes/_Goobstation/Entities/Mobs/Species/yowie.yml
Labels: S: Untriaged, size/S, Changes: No C#

#182 No Longer Crawl Over Tables
  Content.Shared/Standing/StandingStateSystem.cs
Labels: S: Untriaged, size/S

#184 All Species can Crawl/Sneak Under Tables while Prone
  Content.Client/_DV/Abilities/CrawlUnderObjectsSystem.cs
  Content.Server/_DV/Abilities/CrawlUnderObjectsSystem.cs
  Content.Shared/_DV/Abilities/CrawlUnderObjectsComponent.cs
  Content.Shared/_DV/Abilities/SharedCrawlUnderObjectsSystem.cs
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
  Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
  Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
Labels: S: Untriaged, size/M

#156 New alert-level "Dave"
  Resources/Audio/_ShibaStation/Announcements/alert-dave.ogg
  Resources/Audio/_ShibaStation/Announcements/attributions.yml
  Resources/Locale/en-US/_ShibaStation/alert-levels/alert-levels.ftl
  Resources/Prototypes/AlertLevels/alert_levels.yml
Labels: S: Untriaged, S: Needs Review, size/S, Changes: No C#, Changes: Audio

#187 Ariral Species
  Resources/Audio/_ShibaStation/Voice/Ariral/ariral_scream.ogg
  Resources/Audio/_ShibaStation/Voice/Ariral/attributions.yml
  Resources/Locale/en-US/_ShibaStation/chat/managers/chat-manager.ftl
  Resources/Locale/en-US/_ShibaStation/interaction/interaction-popup-component.ftl
  Resources/Locale/en-US/_ShibaStation/markings/ariral.ftl
  Resources/Locale/en-US/_ShibaStation/metabolism/metabolizer-types.ftl
  Resources/Locale/en-US/_ShibaStation/reagents/generic.ftl
  Resources/Locale/en-US/_ShibaStation/reagents/meta/biological.ftl
  Resources/Locale/en-US/_ShibaStation/species/species.ftl
  Resources/Prototypes/Guidebook/species.yml
  Resources/Prototypes/_ShibaStation/Body/Organs/ariral.yml
  Resources/Prototypes/_ShibaStation/Body/Parts/ariral.yml
  Resources/Prototypes/_ShibaStation/Body/Prototypes/ariral.yml
  Resources/Prototypes/_ShibaStation/Chemistry/metabolizer_types.yml
  Resources/Prototypes/_ShibaStation/Damage/modifier_sets.yml
  Resources/Prototypes/_ShibaStation/Datasets/Names/ariral_names.yml
  Resources/Prototypes/_ShibaStation/Entities/Mobs/Customization/Markings/ariral.yml
  Resources/Prototypes/_ShibaStation/Entities/Mobs/Player/ariral.yml
  Resources/Prototypes/_ShibaStation/Entities/Mobs/Species/ariral.yml
  Resources/Prototypes/_ShibaStation/Guidebook/species.yml
  Resources/Prototypes/_ShibaStation/Reagents/biological.yml
  Resources/Prototypes/_ShibaStation/SoundCollections/ariral_emote_soundcollection.yml
  Resources/Prototypes/_ShibaStation/Species/ariral.yml
  Resources/Prototypes/_ShibaStation/Voice/ariral_emote_sounds.yml
  Resources/Prototypes/_ShibaStation/Voice/speech_verbs.yml
  Resources/ServerInfo/Guidebook/Mobs/_ShibaStation/ariral.xml
  Resources/Textures/_ShibaStation/Mobs/Customization/Ariral/ear_markings.rsi/ears.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Ariral/ear_markings.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Customization/Ariral/tail_markings.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Customization/Ariral/tail_markings.rsi/tail.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Ariral/tail_markings.rsi/tail_overlay.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/full.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/head_f.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/head_m.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/l_arm.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/l_foot.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/l_hand.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/l_leg.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/r_arm.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/r_foot.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/r_hand.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/r_leg.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/torso_f.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/torso_m.png
Labels: Changes: Sprites, S: Untriaged, size/L, Changes: No C#, Changes: Audio

#191 Added missing mail carrier spawn to Atlas
  Resources/Maps/_ShibaStation/atlas.yml
Labels: Changes: Map, S: Untriaged, size/M, Changes: No C#

#185 Added Caitlin plushie with half life sfx
  Resources/Audio/_ShibaStation/Effects/sfx/asexpected.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/attributions.yml
  Resources/Audio/_ShibaStation/Effects/sfx/cbar_hit1.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/cbar_hit2.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/fear3.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/greetings.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/heal5.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/hellothere.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/pain3.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/pain4.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/pain5.ogg
  Resources/Audio/_ShibaStation/Effects/sfx/ridiculous.ogg
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_caitlin.yml
  Resources/Prototypes/_ShibaStation/SoundCollections/caitlin_plush_soundcollection.yml
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/caitlin.rsi/icon.png
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/caitlin.rsi/meta.json
Labels: Changes: Sprites, S: Untriaged, size/S, Changes: No C#, Changes: Audio

#194 Tweak Tail Wagging
  Resources/Textures/_White/Mobs/Customization/reptilian_64x32.rsi/meta.json
  Resources/Textures/_White/Mobs/Customization/reptilian_64x32.rsi/snake_large_wagging.png
  Resources/Textures/_White/Mobs/Customization/reptilian_64x32.rsi/snake_large_wagging_overlay.png
Labels: Changes: Sprites, S: Untriaged, size/S, Changes: No C#

#197 Ariral tweaks & fixes
  Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
  Resources/Prototypes/_ShibaStation/Entities/Mobs/Species/ariral.yml
  Resources/Prototypes/_ShibaStation/Reagents/biological.yml
Labels: S: Untriaged, size/S, Changes: No C#

#199 Added missing FootPrints component to Feroxi
  Resources/Prototypes/_DV/Entities/Mobs/Species/feroxi.yml
  Resources/Prototypes/_ShibaStation/Entities/Mobs/Species/ariral.yml
Labels: size/XS, Changes: No C#

#200 Added Classic Stilettos
  Resources/Locale/en-US/preferences/loadout-groups.ftl
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/_ShibaStation/Entities/Clothing/Shoes/classic_stilettos.yml
  Resources/Prototypes/_ShibaStation/Loadouts/Jobs/Command/command.yml
  Resources/Textures/_ShibaStation/Clothing/Shoes/classic_stilettos.rsi/equipped-FEET.png
  Resources/Textures/_ShibaStation/Clothing/Shoes/classic_stilettos.rsi/icon-preview.png
  Resources/Textures/_ShibaStation/Clothing/Shoes/classic_stilettos.rsi/icon.png
  Resources/Textures/_ShibaStation/Clothing/Shoes/classic_stilettos.rsi/inhand-left.png
  Resources/Textures/_ShibaStation/Clothing/Shoes/classic_stilettos.rsi/inhand-right.png
  Resources/Textures/_ShibaStation/Clothing/Shoes/classic_stilettos.rsi/meta.json
Labels: Changes: Sprites, S: Untriaged, size/M, Changes: No C#

#203 Revert "proximity airlock opening (#2076)"
  Content.Shared/Doors/Components/DoorComponent.cs
  Content.Shared/Doors/Systems/SharedDoorSystem.cs
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
Labels: S: Untriaged, size/S

#202 Holsters can now be worn on your outerwear slot
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Textures/Clothing/Belt/holster.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/Belt/holster.rsi/meta.json
  Resources/Textures/Clothing/Belt/syndieholster.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/Belt/syndieholster.rsi/meta.json
Labels: Changes: Sprites, size/S, Changes: No C#
