Repository AstroDogeDX/ShibaStation-GS, pull requests merged in 2025-02, with the labels that each got.

#87 NT Rep & BSO Tidy Up and Fixes
  Resources/Locale/en-US/job/department-desc.ftl
  Resources/Locale/en-US/job/department.ftl
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
  Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
  Resources/Prototypes/_ShibaStation/Roles/Jobs/Cargo/mail_carrier.yml
  Resources/Textures/Objects/Misc/id_cards.rsi/idblueshield.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idntrep.png
  Resources/Textures/Objects/Misc/id_cards.rsi/meta.json
Labels: Changes: Sprites, S: Untriaged, size/S, Changes: No C#

#88 Revert "[PORT] Vent Critters Rework from Delta-V (#1450)"
  Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs
  Content.Server/StationEvents/Events/VentCrittersRule.cs
  Resources/Locale/en-US/deltav/station-events/events/vent-critters.ftl
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/pests.yml
Labels: S: Untriaged, size/M

#90 Increased Min Pop Reqs for Some Events... Again
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
  Resources/Prototypes/_ShibaStation/GameRules/events.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#91 Added 'Cycling' Mode to Air Alarms
  Content.Client/Atmos/Monitor/UI/AirAlarmWindow.xaml.cs
  Content.Server/Atmos/Monitor/Systems/AirAlarmModes.cs
  Content.Shared/Atmos/Monitor/Components/SharedAirAlarmComponent.cs
  Resources/Locale/en-US/atmos/air-alarm-ui.ftl
Labels: Changes: UI, S: Untriaged, size/S

#92 Add air scrubbers to the Cargo and Mining shuttles
  Resources/Maps/Shuttles/cargo.yml
  Resources/Maps/Shuttles/mining.yml
Labels: Changes: Map, S: Untriaged, size/M, Changes: No C#

#93 Adds --hidden argument to aghost command
  Content.Server/Administration/Commands/AGhostCommand.cs
  Content.Shared/Ghost/SharedGhostSystem.cs
Labels: S: Untriaged, size/S

#94 Big Cleaning Update
  Content.Server/Chemistry/TileReactions/CleanTileReaction.cs
  Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
  Content.Shared/Fluids/AbsorbentComponent.cs
  Resources/Locale/en-US/fluids/components/absorbent-component.ftl
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
  Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
  Resources/Prototypes/_ShibaStation/Entities/Mobs/NPCs/silicon.yml
  Resources/Prototypes/_White/Entities/Effects/puddle.yml
Labels: S: Untriaged, size/M

#96 Readded custom voice announcement for category 5 vent spawns
  Resources/Prototypes/GameRules/events.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#101 Adjust Air Alarm Threshold Defaults
  Resources/Prototypes/Atmospherics/thresholds.yml
Labels: S: Untriaged, Changes: No C#

#102 Fixed a missing linebreak that was breaking formatting, oopsie
  Resources/ServerInfo/_ShibaStation/Guidebook/ServerRules/CoreRules/ShibaRuleC4BeCivil.xml
Labels: S: Untriaged, size/XS, Changes: No C#

#98 [Cluster] Surgery, Morgue and Atmos have been reworked. TEG was added to Atmos
  Resources/Maps/_ShibaStation/cluster.yml
Labels: Changes: Map, S: Untriaged, S: Needs Review, size/XL, Changes: No C#

#103 Adds 'snouse' mob
  Resources/Prototypes/_ShibaStation/Entities/Mobs/NPCs/animals.yml
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/dead.png
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/equipped-HELMET.png
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/icon.png
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/inhand-left.png
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/inhand-right.png
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/snouse.png
  Resources/Textures/_ShibaStation/Mobs/Animals/snouse.rsi/splat.png
Labels: Changes: Sprites, S: Untriaged, size/S, Changes: No C#

#99 [Atlas] Various map tweaks and improvements
  Resources/Maps/_ShibaStation/atlas.yml
  Resources/Prototypes/_Goobstation/Maps/atlas.yml
Labels: Changes: Map, size/L, Changes: No C#

#104 Added some wonderful lobby art and music from our community!
  Resources/Audio/_ShibaStation/Lobby/attributions.yml
  Resources/Audio/_ShibaStation/Lobby/ttotm_but_waiting_for_shuttle.ogg
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/_ShibaStation/LobbyScreens/attributions.yml
  Resources/Textures/_ShibaStation/LobbyScreens/revenant.webp
  Resources/Textures/_ShibaStation/LobbyScreens/revenant.webp.yml
  Resources/Textures/_ShibaStation/LobbyScreens/singuloose.webp
  Resources/Textures/_ShibaStation/LobbyScreens/singuloose.webp.yml
Labels: S: Untriaged, size/S, Changes: No C#, Changes: Audio

#105 Add new lobby music track
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#100 [Salvage Shuttle] Fix missing HV cable + free air canister
  Resources/Maps/Shuttles/mining.yml
Labels: Changes: Map, size/S, Changes: No C#

#108 Abductor upgrades for Scientist/Agent
  Resources/Prototypes/_Shitmed/Entities/Objects/Weapons/Melee/wonderprod.yml
  Resources/Prototypes/_Shitmed/GameRules/events.yml
Labels: S: Untriaged, size/S, Changes: No C#

#107 Greatly adjusts antag/ghost role time requirements
  Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/behonker.yml
  Resources/Prototypes/Entities/Mobs/NPCs/elemental.yml
  Resources/Prototypes/Entities/Mobs/NPCs/hellspawn.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
  Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
  Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
  Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
  Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
  Resources/Prototypes/Entities/Mobs/Player/dragon.yml
  Resources/Prototypes/Entities/Mobs/Player/familiars.yml
  Resources/Prototypes/Entities/Mobs/Player/guardian.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Mobs/Player/skeleton.yml
  Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/reinforcement_teleporter.yml
  Resources/Prototypes/Roles/Antags/dragon.yml
  Resources/Prototypes/Roles/Antags/ninja.yml
  Resources/Prototypes/Roles/Antags/nukeops.yml
  Resources/Prototypes/Roles/Antags/revolutionary.yml
  Resources/Prototypes/Roles/Antags/silicon.yml
  Resources/Prototypes/Roles/Antags/thief.yml
  Resources/Prototypes/Roles/Antags/traitor.yml
  Resources/Prototypes/Roles/Antags/zombie.yml
  Resources/Prototypes/XenoArch/Effects/utility_effects.yml
  Resources/Prototypes/_Goobstation/Blob/blob_mobs.yml
  Resources/Prototypes/_Goobstation/Blob/blob_tiles.yml
  Resources/Prototypes/_Goobstation/Blob/misc_blob.yml
  Resources/Prototypes/_Goobstation/Changeling/Roles/Antags/changeling.yml
  Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/_Goobstation/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Devices/Syndicate_Gadgets/reinforcement_teleporter.yml
  Resources/Prototypes/_Goobstation/Heretic/Roles/Antags/heretic.yml
  Resources/Prototypes/_Goobstation/Roles/Antags/blob.yml
  Resources/Prototypes/_Goobstation/Wizard/wizard.yml
  Resources/Prototypes/_Shitmed/Entities/Mobs/Player/abductor.yml
  Resources/Prototypes/_Shitmed/Roles/Antags/abductor.yml
Labels: size/M, Changes: No C#

#109 GOODBYE YOU WILL NOT BE MISS (Removed Reach)
  Resources/Prototypes/Maps/Pools/default.yml
Labels: Changes: Map, S: Untriaged, size/XS, Changes: No C#

#110 16:9 versions, forgot to add them before merging OOPSIE
  Resources/Textures/_ShibaStation/LobbyScreens/revenant.webp
  Resources/Textures/_ShibaStation/LobbyScreens/singuloose.webp
Labels: S: Untriaged, size/XS, Changes: No C#

#111 Added the snouse to the vent spawns
  Resources/Prototypes/_ShibaStation/GameRules/events.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#112 Antag reqs tweaks
  Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/_Goobstation/Wizard/wizard.yml
Labels: S: Untriaged, size/S, Changes: No C#

#113 Rodentians are mousetrap-proof
  Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
Labels: Changes: No C#

#114 Snouse fixes
  Resources/Prototypes/_ShibaStation/Entities/Mobs/NPCs/animals.yml
Labels: S: Untriaged, size/M, Changes: No C#

#117 Revising Description of Ambuzol+
  Resources/Locale/en-US/reagents/meta/medicine.ftl
Labels: S: Untriaged, size/XS, Changes: No C#

#120 Symmetrise the Lavaland Shuttle
  Resources/Maps/_Lavaland/mining.yml
Labels: Changes: Map, size/S, Changes: No C#

#121 Salvage Locator on Salvage Shuttle (Salvage Magnet removed from Stations)
  Resources/Maps/Shuttles/mining.yml
  Resources/migration.yml
Labels: Changes: Map, S: Untriaged, size/S, Changes: No C#

#122 Lavaland name tweaks
  Resources/Locale/en-US/_Lavaland/salvage/lavaland_names.ftl
  Resources/Maps/_Lavaland/mining.yml
Labels: Changes: Map, S: Untriaged, size/XS, Changes: No C#

#123 AdminAccess Group (+ Fixes)
  Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
  Resources/Prototypes/Entities/Objects/Devices/door_remote.yml
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/_ShibaStation/Access/admin.yml
Labels: S: Untriaged, size/S, Changes: No C#

#126 Fix Vox Air Alarms
  Resources/Prototypes/Entities/Structures/Specific/Atmospherics/vox.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#127 More Things Equip Over Clothing
  Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml
  Resources/Prototypes/_EinsteinEngines/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/specific.yml
  Resources/Prototypes/_Lavaland/Entities/Clothing/explorer_suit.yml
Labels: S: Untriaged, size/S, Changes: No C#

#128 Removed theobromine's poison effect on animal organs (by vote)
  Resources/Prototypes/Reagents/toxins.yml
Labels: S: Untriaged, Changes: No C#

#129 Elkridge + Map Edits + Lavaland Console Rename
  Resources/Locale/en-US/deltav/shuttles/docking-console.ftl
  Resources/Maps/Shuttles/cargo_elkridge.yml
  Resources/Maps/Shuttles/emergency_elkridge.yml
  Resources/Maps/Shuttles/mining.yml
  Resources/Maps/_ShibaStation/amber.yml
  Resources/Maps/_ShibaStation/atlas.yml
  Resources/Maps/_ShibaStation/cluster.yml
  Resources/Maps/_ShibaStation/elkridge.yml
  Resources/Maps/_ShibaStation/omega.yml
  Resources/Maps/_ShibaStation/packed.yml
  Resources/Maps/_ShibaStation/saltern.yml
  Resources/Maps/elkridge.yml
  Resources/Maps/omega.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/elkridge.yml
  Resources/Prototypes/_Lavaland/Entities/Structures/computers.yml
Labels: Changes: Map, S: Untriaged, size/XL, Changes: No C#

#125 New Plushies + Lobby BG
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_achto.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_cass.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_dave.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_deroh.yml
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_lucy.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/_ShibaStation/LobbyScreens/attributions.yml
  Resources/Textures/_ShibaStation/LobbyScreens/eating_bullets.webp
  Resources/Textures/_ShibaStation/LobbyScreens/eating_bullets.webp.yml
  Resources/Textures/_ShibaStation/LobbyScreens/police_brutality.webp
  Resources/Textures/_ShibaStation/LobbyScreens/police_brutality.webp.yml
  Resources/Textures/_ShibaStation/LobbyScreens/revenant.webp
  Resources/Textures/_ShibaStation/LobbyScreens/singuloose.webp
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/achto.rsi/icon.png
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/achto.rsi/meta.json
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/cass.rsi/icon.png
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/cass.rsi/meta.json
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/dave.rsi/icon.png
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/dave.rsi/meta.json
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/deroh.rsi/icon.png
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/deroh.rsi/meta.json
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/lucy.rsi/icon.png
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/lucy.rsi/meta.json
Labels: Changes: Sprites, S: Untriaged, S: Needs Review, size/M, Changes: No C#

#130 Unique screen overlays for lavaland shuttle and salvage shuttle consoles
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/_Lavaland/Entities/Structures/computers.yml
Labels: S: Untriaged, size/XS, Changes: No C#

#131 [Cluster] Removed some lattice that made docking the salv shuttle impossible
  Resources/Maps/_ShibaStation/cluster.yml
Labels: Changes: Map, S: Untriaged, size/S, Changes: No C#
