Repository AstroDogeDX/ShibaStation-GS, pull requests merged in 2025-04, with the labels that each got.

#221 Addition of resomi salvager Lavaland explorer suit
  Resources/Prototypes/_Lavaland/Entities/Clothing/explorer_suit.yml
  Resources/Textures/Clothing/Mask/gasexplorer.rsi/equipped-MASK-resomi.png
  Resources/Textures/Clothing/Mask/gasexplorer.rsi/meta.json
  Resources/Textures/Clothing/Mask/gasexplorer.rsi/up-equipped-MASK-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/equipped-HELMET-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/equipped-OUTERCLOTHING-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/meta.json
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/reinforced1-equipped-HELMET-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/reinforced1-equipped-OUTERCLOTHING-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/reinforced2-equipped-HELMET-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/reinforced2-equipped-OUTERCLOTHING-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/reinforced3-equipped-HELMET-resomi.png
  Resources/Textures/_Lavaland/Equipment/explorer_suit.rsi/reinforced3-equipped-OUTERCLOTHING-resomi.png
Labels: Changes: Sprites, S: Untriaged, size/M, Changes: No C#

#219 Fixes the mysterious case of Disappearing Office Chairs from maps after they get an update.
  Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
Labels: S: Untriaged, Changes: No C#

#205 sevan plushie
  Resources/Prototypes/_ShibaStation/Entities/Objects/Fun/ShibPlush/plushie_sevan.yml
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/sevan.rsi/icon.png
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/sevan.rsi/meta.json
  Resources/Textures/_ShibaStation/Objects/Fun/ShibPlush/sevan.rsi/mug.png
Labels: Changes: Sprites, S: Untriaged, S: Needs Review, size/S, Changes: No C#

#217 Issue #210: Remaps silo to vault
  Resources/Maps/_ShibaStation/amber.yml
  Resources/Maps/_ShibaStation/atlas.yml
  Resources/Maps/_ShibaStation/cluster.yml
  Resources/Maps/_ShibaStation/elkridge.yml
  Resources/Maps/_ShibaStation/omega.yml
  Resources/Maps/_ShibaStation/packed.yml
  Resources/Maps/_ShibaStation/saltern.yml
Labels: Changes: Map, size/M, Changes: No C#

#224 Midround Antag Rebalancing
  Content.Goobstation.Shared/Changeling/Components/ChangelingIdentityComponent.cs
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/_Goobstation/Changeling/Objectives/changeling.yml
  Resources/Prototypes/_Goobstation/GameRules/midround.yml
  Resources/Prototypes/_Goobstation/Heretic/Objectives/heretic.yml
  Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml
  Resources/Prototypes/_Shitmed/GameRules/events.yml
Labels: S: Untriaged, size/S

#228 Reduce tendon health down from 40 to 12
  Resources/Prototypes/Entities/Objects/Misc/kudzu.yml
Labels: size/XS, Changes: No C#

#229 Switch to GH runner instead of self-hosted
  .github/workflows/changelog.yml
Labels: S: Untriaged, size/S, Changes: No C#

#230 Give Command access to Cappy's Room under Extended Access conditions
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
Labels: Changes: No C#

#231 No Dead Chat from Summon Ghosts Spell
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/_Shitcode/Wizard/Systems/GhostVisibilitySystem.cs
Labels: S: Untriaged, size/S

#233 Goob patch
  Content.Goobstation.Server/Fishing/FishingSystem.cs
  Content.Goobstation.Shared/Fishing/Systems/SharedFishingSystem.cs
  Resources/Changelog/GoobChangelog.yml
  Resources/Locale/en-US/_Goobstation/servercurrency/server_currency.ftl
  Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml
Labels: S: Untriaged, size/M
