Repository AstroDogeDX/ShibaStation-GS, pull requests merged in 2025-05, with the labels that each got.

#240 Resomi Hair and Markings + Adjustments
  Resources/Locale/en-US/_Floofstation/accessories/resomi-hair.ftl
  Resources/Locale/en-US/_Floofstation/markings/resomi.ftl
  Resources/Prototypes/_Floofstation/Entities/Mobs/Customization/Markings/resomi.yml
  Resources/Prototypes/_Floofstation/Entities/Mobs/Customization/Markings/resomi_hair.yml
  Resources/Prototypes/_Floofstation/Species/resomi.yml
  Resources/Textures/_EinsteinEngines/Mobs/Species/Cybernetics/bishop/bishop_main.rsi/l-arm-combined-resomi.png
  Resources/Textures/_EinsteinEngines/Mobs/Species/Cybernetics/bishop/bishop_main.rsi/l-hand-resomi.png
  Resources/Textures/_EinsteinEngines/Mobs/Species/Cybernetics/bishop/bishop_main.rsi/meta.json
  Resources/Textures/_EinsteinEngines/Mobs/Species/Cybernetics/bishop/bishop_main.rsi/r-arm-combined-resomi.png
  Resources/Textures/_EinsteinEngines/Mobs/Species/Cybernetics/bishop/bishop_main.rsi/r-hand-resomi.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/arm_markings.rsi/cyberkinetic-arm-l-full.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/arm_markings.rsi/cyberkinetic-arm-l.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/arm_markings.rsi/cyberkinetic-arm-r-full.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/arm_markings.rsi/cyberkinetic-arm-r.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/arm_markings.rsi/cyberkinetic-hand-l.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/arm_markings.rsi/cyberkinetic-hand-r.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/arm_markings.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/head_markings.rsi/Wendigo-onlypaint.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/head_markings.rsi/Wendigo-paint-mane.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/head_markings.rsi/Wendigo-paint.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/head_markings.rsi/fluff_ears.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/head_markings.rsi/fluff_ears_botonly.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/head_markings.rsi/fluff_ears_toponly.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/head_markings.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/leg_markings.rsi/cyberkinetic-foot-l.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/leg_markings.rsi/cyberkinetic-foot-r.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/leg_markings.rsi/cyberkinetic-leg-l.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/leg_markings.rsi/cyberkinetic-leg-r.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/leg_markings.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiCosmorunner.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiGenericallyUnique.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiLoyal.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiLoyalMale.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiPlumage.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiPlumageLong.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiRebel.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/ResomiRebelExtended.png
  Resources/Textures/_ShibaStation/Mobs/Customization/Resomi/resomi_hair.rsi/meta.json
Labels: Changes: Sprites, size/M, Changes: No C#

#213 Blueshield's Towel
  Resources/Prototypes/Entities/Clothing/Multiple/towel.yml
  Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: S: Untriaged, size/S, Changes: No C#

#245 Feroxi/Ariral Woundmed Patch 1
  Resources/Prototypes/_DV/Body/Parts/feroxi.yml
  Resources/Prototypes/_DV/Body/Prototypes/feroxi.yml
  Resources/Prototypes/_DV/Species/feroxi.yml
  Resources/Prototypes/_ShibaStation/Body/Parts/ariral.yml
  Resources/Prototypes/_ShibaStation/Body/Prototypes/ariral.yml
  Resources/Prototypes/_ShibaStation/Species/ariral.yml
  Resources/Textures/_DV/Mobs/Species/Feroxi/parts.rsi/chest_f.png
  Resources/Textures/_DV/Mobs/Species/Feroxi/parts.rsi/chest_m.png
  Resources/Textures/_DV/Mobs/Species/Feroxi/parts.rsi/groin_f.png
  Resources/Textures/_DV/Mobs/Species/Feroxi/parts.rsi/groin_m.png
  Resources/Textures/_DV/Mobs/Species/Feroxi/parts.rsi/meta.json
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/chest_f.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/chest_m.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/groin_f.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/groin_m.png
  Resources/Textures/_ShibaStation/Mobs/Species/Ariral/parts.rsi/meta.json
Labels: Changes: Sprites, S: Untriaged, size/M, Changes: No C#

#251 Removed Dynamic Hostname
  Content.Goobstation.Common/CCVar/CCVars.Goob.cs
  Content.Goobstation.Server/Hostname/DynamicHostnameSystem.cs
Labels: S: Untriaged, size/S
